project:
  type: website
  # output-dir: docs
execute: 
  freeze: auto  # Re-render only when source changes
  cache: true

website:
  title: "MyLabJournal"
  favicon: assets/icons/favicon.svg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Journal"
        menu: 
          - text: "Machine Learning Fundamentals"
            file: content/MLFund/01_MLFunds.qmd
          - text: "Supervised ML - Regression 02"
            file: content/SMLReg2/Regression.qmd
          - text: "Automated ML 01"
            file: content/SMLReg2/Regression.qmd
          - text: "Automated ML 02"
            file: content/SMLReg2/Regression.qmd
          - text: "Performance Measures"
            file: content/SMLReg2/Regression.qmd
          - text: "Black Box Models"
            file: content/SMLReg2/Regression.qmd
          - text: "Deep Learning"
            file: content/SMLReg2/Regression.qmd
      - text: "Class notes"
        file: content/02_notes/05_class_notes.qmd
      - text: "Links"
        file: content/03_other/06_links.qmd

format:
  html:
    theme:
      dark: darkly
      light: flatly
    highlight-style: a11y-dark
filters:
   - lightbox
lightbox: auto